//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infolog", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Infolog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.InfologEntry[] EntriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.InfologEntry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologEntry", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class InfologEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.InfologType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.InfologType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologType", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    public enum InfologType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="AX365_DIRECT_IMPORT.ImportSuiteData")]
    public interface ImportSuiteData {
        
        // CODEGEN: Generating message contract since message PANGEA_import_v2 has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteData/PANGEA_import_v2", ReplyAction="http://tempuri.org/ImportSuiteData/PANGEA_import_v2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Fault), Action="http://tempuri.org/ImportSuiteData/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_import_v2Response PANGEA_import_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_import_v2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteData/PANGEA_import_v2", ReplyAction="http://tempuri.org/ImportSuiteData/PANGEA_import_v2Response")]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_import_v2Response> PANGEA_import_v2Async(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_import_v2 request);
        
        // CODEGEN: Generating message contract since message PANGEA_validate_v2 has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteData/PANGEA_validate_v2", ReplyAction="http://tempuri.org/ImportSuiteData/PANGEA_validate_v2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Fault), Action="http://tempuri.org/ImportSuiteData/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_validate_v2Response PANGEA_validate_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_validate_v2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteData/PANGEA_validate_v2", ReplyAction="http://tempuri.org/ImportSuiteData/PANGEA_validate_v2Response")]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_validate_v2Response> PANGEA_validate_v2Async(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_validate_v2 request);
        
        // CODEGEN: Generating message contract since message PANGEA_process_v2 has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteData/PANGEA_process_v2", ReplyAction="http://tempuri.org/ImportSuiteData/PANGEA_process_v2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Fault), Action="http://tempuri.org/ImportSuiteData/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_process_v2Response PANGEA_process_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_process_v2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteData/PANGEA_process_v2", ReplyAction="http://tempuri.org/ImportSuiteData/PANGEA_process_v2Response")]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_process_v2Response> PANGEA_process_v2Async(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_process_v2 request);
        
        // CODEGEN: Generating message contract since message PANGEA_showrecords_v2 has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteData/PANGEA_showrecords_v2", ReplyAction="http://tempuri.org/ImportSuiteData/PANGEA_showrecords_v2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Fault), Action="http://tempuri.org/ImportSuiteData/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_showrecords_v2Response PANGEA_showrecords_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_showrecords_v2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteData/PANGEA_showrecords_v2", ReplyAction="http://tempuri.org/ImportSuiteData/PANGEA_showrecords_v2Response")]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_showrecords_v2Response> PANGEA_showrecords_v2Async(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_showrecords_v2 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_import_v2", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_import_v2 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _parmCompany;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _parmFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _parmGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string _parmModule;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public string _parmSeparator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=5)]
        public string _parmURLFileCSV;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=6)]
        public string _parmUserId;
        
        public PANGEA_import_v2() {
        }
        
        public PANGEA_import_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext, string _parmCompany, string _parmFileName, string _parmGUID, string _parmModule, string _parmSeparator, string _parmURLFileCSV, string _parmUserId) {
            this.CallContext = CallContext;
            this._parmCompany = _parmCompany;
            this._parmFileName = _parmFileName;
            this._parmGUID = _parmGUID;
            this._parmModule = _parmModule;
            this._parmSeparator = _parmSeparator;
            this._parmURLFileCSV = _parmURLFileCSV;
            this._parmUserId = _parmUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_import_v2Response", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_import_v2Response {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string result;
        
        public PANGEA_import_v2Response() {
        }
        
        public PANGEA_import_v2Response(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Infolog Infolog, string result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_validate_v2", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_validate_v2 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _parmCompany;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _parmGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _parmModule;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string _parmValidate;
        
        public PANGEA_validate_v2() {
        }
        
        public PANGEA_validate_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmModule, string _parmValidate) {
            this.CallContext = CallContext;
            this._parmCompany = _parmCompany;
            this._parmGUID = _parmGUID;
            this._parmModule = _parmModule;
            this._parmValidate = _parmValidate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_validate_v2Response", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_validate_v2Response {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string result;
        
        public PANGEA_validate_v2Response() {
        }
        
        public PANGEA_validate_v2Response(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Infolog Infolog, string result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_process_v2", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_process_v2 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _parmCompany;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _parmGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _parmJournal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string _parmModule;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public string _parmUserId;
        
        public PANGEA_process_v2() {
        }
        
        public PANGEA_process_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmJournal, string _parmModule, string _parmUserId) {
            this.CallContext = CallContext;
            this._parmCompany = _parmCompany;
            this._parmGUID = _parmGUID;
            this._parmJournal = _parmJournal;
            this._parmModule = _parmModule;
            this._parmUserId = _parmUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_process_v2Response", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_process_v2Response {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string result;
        
        public PANGEA_process_v2Response() {
        }
        
        public PANGEA_process_v2Response(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Infolog Infolog, string result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_showrecords_v2", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_showrecords_v2 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _parmCompany;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _parmGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _parmModule;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string _parmRegType;
        
        public PANGEA_showrecords_v2() {
        }
        
        public PANGEA_showrecords_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmModule, string _parmRegType) {
            this.CallContext = CallContext;
            this._parmCompany = _parmCompany;
            this._parmGUID = _parmGUID;
            this._parmModule = _parmModule;
            this._parmRegType = _parmRegType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_showrecords_v2Response", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_showrecords_v2Response {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string result;
        
        public PANGEA_showrecords_v2Response() {
        }
        
        public PANGEA_showrecords_v2Response(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Infolog Infolog, string result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImportSuiteDataChannel : PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImportSuiteDataClient : System.ServiceModel.ClientBase<PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData>, PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData {
        
        public ImportSuiteDataClient() {
        }
        
        public ImportSuiteDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImportSuiteDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportSuiteDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportSuiteDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_import_v2Response PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData.PANGEA_import_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_import_v2 request) {
            return base.Channel.PANGEA_import_v2(request);
        }
        
        public PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Infolog PANGEA_import_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext, string _parmCompany, string _parmFileName, string _parmGUID, string _parmModule, string _parmSeparator, string _parmURLFileCSV, string _parmUserId, out string result) {
            PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_import_v2 inValue = new PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_import_v2();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmFileName = _parmFileName;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmSeparator = _parmSeparator;
            inValue._parmURLFileCSV = _parmURLFileCSV;
            inValue._parmUserId = _parmUserId;
            PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_import_v2Response retVal = ((PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData)(this)).PANGEA_import_v2(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_import_v2Response> PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData.PANGEA_import_v2Async(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_import_v2 request) {
            return base.Channel.PANGEA_import_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_import_v2Response> PANGEA_import_v2Async(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext, string _parmCompany, string _parmFileName, string _parmGUID, string _parmModule, string _parmSeparator, string _parmURLFileCSV, string _parmUserId) {
            PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_import_v2 inValue = new PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_import_v2();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmFileName = _parmFileName;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmSeparator = _parmSeparator;
            inValue._parmURLFileCSV = _parmURLFileCSV;
            inValue._parmUserId = _parmUserId;
            return ((PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData)(this)).PANGEA_import_v2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_validate_v2Response PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData.PANGEA_validate_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_validate_v2 request) {
            return base.Channel.PANGEA_validate_v2(request);
        }
        
        public PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Infolog PANGEA_validate_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmModule, string _parmValidate, out string result) {
            PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_validate_v2 inValue = new PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_validate_v2();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmValidate = _parmValidate;
            PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_validate_v2Response retVal = ((PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData)(this)).PANGEA_validate_v2(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_validate_v2Response> PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData.PANGEA_validate_v2Async(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_validate_v2 request) {
            return base.Channel.PANGEA_validate_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_validate_v2Response> PANGEA_validate_v2Async(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmModule, string _parmValidate) {
            PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_validate_v2 inValue = new PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_validate_v2();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmValidate = _parmValidate;
            return ((PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData)(this)).PANGEA_validate_v2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_process_v2Response PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData.PANGEA_process_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_process_v2 request) {
            return base.Channel.PANGEA_process_v2(request);
        }
        
        public PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Infolog PANGEA_process_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmJournal, string _parmModule, string _parmUserId, out string result) {
            PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_process_v2 inValue = new PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_process_v2();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmGUID = _parmGUID;
            inValue._parmJournal = _parmJournal;
            inValue._parmModule = _parmModule;
            inValue._parmUserId = _parmUserId;
            PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_process_v2Response retVal = ((PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData)(this)).PANGEA_process_v2(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_process_v2Response> PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData.PANGEA_process_v2Async(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_process_v2 request) {
            return base.Channel.PANGEA_process_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_process_v2Response> PANGEA_process_v2Async(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmJournal, string _parmModule, string _parmUserId) {
            PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_process_v2 inValue = new PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_process_v2();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmGUID = _parmGUID;
            inValue._parmJournal = _parmJournal;
            inValue._parmModule = _parmModule;
            inValue._parmUserId = _parmUserId;
            return ((PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData)(this)).PANGEA_process_v2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_showrecords_v2Response PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData.PANGEA_showrecords_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_showrecords_v2 request) {
            return base.Channel.PANGEA_showrecords_v2(request);
        }
        
        public PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.Infolog PANGEA_showrecords_v2(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmModule, string _parmRegType, out string result) {
            PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_showrecords_v2 inValue = new PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_showrecords_v2();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmRegType = _parmRegType;
            PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_showrecords_v2Response retVal = ((PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData)(this)).PANGEA_showrecords_v2(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_showrecords_v2Response> PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData.PANGEA_showrecords_v2Async(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_showrecords_v2 request) {
            return base.Channel.PANGEA_showrecords_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_showrecords_v2Response> PANGEA_showrecords_v2Async(PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmModule, string _parmRegType) {
            PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_showrecords_v2 inValue = new PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.PANGEA_showrecords_v2();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmRegType = _parmRegType;
            return ((PANGEA.IMPORTSUITE.DataModel.AX365_DIRECT_IMPORT.ImportSuiteData)(this)).PANGEA_showrecords_v2Async(inValue);
        }
    }
}
