//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PANGEA.IMPORTSUITE.DataModel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=MPA;User ID=sa;Password=2289")]
        public string MPAConnectionString {
            get {
                return ((string)(this["MPAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=PANGEA_IMPORT_SUITE;User ID=sa;Password=2289")]
        public string PANGEA_IMPORT_SUITEConnectionString {
            get {
                return ((string)(this["PANGEA_IMPORT_SUITEConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local)\\SQL2014;Initial Catalog=PANGEA_IMPORT_SUITE;User ID=sa;Passwo" +
            "rd=2289")]
        public string PANGEA_IMPORT_SUITEConnectionString1 {
            get {
                return ((string)(this["PANGEA_IMPORT_SUITEConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQLDEVLATAM;Initial Catalog=PANGEA_IMPORTSUITE_LATAM;User ID=pangea_a" +
            "x;Password=pangea_4x")]
        public string PANGEA_IMPORTSUITE_LATAMConnectionString {
            get {
                return ((string)(this["PANGEA_IMPORTSUITE_LATAMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local)\\SQL2014;Initial Catalog=PANGEA_IMPORTSUITE_LATAM;User ID=sa;P" +
            "assword=2289")]
        public string PANGEA_IMPORTSUITE_LATAMConnectionString1 {
            get {
                return ((string)(this["PANGEA_IMPORTSUITE_LATAMConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=PANGEA_IMPORTSUITE_LATAM;User ID=sa;Password=" +
            "2289")]
        public string PANGEA_IMPORTSUITE_LATAMConnectionString2 {
            get {
                return ((string)(this["PANGEA_IMPORTSUITE_LATAMConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SVRSQLUAT;Initial Catalog=PANGEA_IMPORTSUITE_LATAM;User ID=pangea_ax;" +
            "Password=pangea_4x")]
        public string PANGEA_IMPORTSUITE_LATAMConnectionString3 {
            get {
                return ((string)(this["PANGEA_IMPORTSUITE_LATAMConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ax-dev-web-01:9090/wsAdminFiles.asmx")]
        public string PANGEA_IMPORTSUITE_DataModel_MPA_RECONCILE_WS_wsAdminFiles {
            get {
                return ((string)(this["PANGEA_IMPORTSUITE_DataModel_MPA_RECONCILE_WS_wsAdminFiles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AX-TEST-SQL-01\\MSSQLSERVER_TEST;Initial Catalog=MPA_ImportSuite;User " +
            "ID=sa;Password=P@ssword1")]
        public string MPA_ImportSuiteConnectionString {
            get {
                return ((string)(this["MPA_ImportSuiteConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AX-DEV-SQL-01;Initial Catalog=MPA_ImportSuite;User ID=sa;Password=P@s" +
            "sword1")]
        public string MPA_ImportSuiteConnectionString1 {
            get {
                return ((string)(this["MPA_ImportSuiteConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AX-TEST-SQL-01;Initial Catalog=MPA_ImportSuite;User ID=sa;Password=P@" +
            "ssword1")]
        public string MPA_ImportSuiteConnectionString2 {
            get {
                return ((string)(this["MPA_ImportSuiteConnectionString2"]));
            }
        }
    }
}
