//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogonAsUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser {
            get {
                return this.LogonAsUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LogonAsUserField, value) != true)) {
                    this.LogonAsUserField = value;
                    this.RaisePropertyChanged("LogonAsUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag {
            get {
                return this.PropertyBagField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyBagField, value) != true)) {
                    this.PropertyBagField = value;
                    this.RaisePropertyChanged("PropertyBag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class AifFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomDetailXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.FaultMessageList[] FaultMessageListArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.InfologMessage[] InfologMessageListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XppExceptionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml {
            get {
                return this.CustomDetailXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDetailXmlField, value) != true)) {
                    this.CustomDetailXmlField = value;
                    this.RaisePropertyChanged("CustomDetailXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.FaultMessageList[] FaultMessageListArray {
            get {
                return this.FaultMessageListArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageListArrayField, value) != true)) {
                    this.FaultMessageListArrayField = value;
                    this.RaisePropertyChanged("FaultMessageListArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.InfologMessage[] InfologMessageList {
            get {
                return this.InfologMessageListField;
            }
            set {
                if ((object.ReferenceEquals(this.InfologMessageListField, value) != true)) {
                    this.InfologMessageListField = value;
                    this.RaisePropertyChanged("InfologMessageList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType {
            get {
                return this.XppExceptionTypeField;
            }
            set {
                if ((this.XppExceptionTypeField.Equals(value) != true)) {
                    this.XppExceptionTypeField = value;
                    this.RaisePropertyChanged("XppExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessageList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.FaultMessage[] FaultMessageArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlPositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation {
            get {
                return this.DocumentOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentOperationField, value) != true)) {
                    this.DocumentOperationField = value;
                    this.RaisePropertyChanged("DocumentOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.FaultMessage[] FaultMessageArray {
            get {
                return this.FaultMessageArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageArrayField, value) != true)) {
                    this.FaultMessageArrayField = value;
                    this.RaisePropertyChanged("FaultMessageArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation {
            get {
                return this.ServiceOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationField, value) != true)) {
                    this.ServiceOperationField = value;
                    this.RaisePropertyChanged("ServiceOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter {
            get {
                return this.ServiceOperationParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationParameterField, value) != true)) {
                    this.ServiceOperationParameterField = value;
                    this.RaisePropertyChanged("ServiceOperationParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath {
            get {
                return this.XPathField;
            }
            set {
                if ((object.ReferenceEquals(this.XPathField, value) != true)) {
                    this.XPathField = value;
                    this.RaisePropertyChanged("XPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine {
            get {
                return this.XmlLineField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlLineField, value) != true)) {
                    this.XmlLineField = value;
                    this.RaisePropertyChanged("XmlLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition {
            get {
                return this.XmlPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlPositionField, value) != true)) {
                    this.XmlPositionField = value;
                    this.RaisePropertyChanged("XmlPosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    [System.SerializableAttribute()]
    public partial class InfologMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.InfologMessageType InfologMessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.InfologMessageType InfologMessageType {
            get {
                return this.InfologMessageTypeField;
            }
            set {
                if ((this.InfologMessageTypeField.Equals(value) != true)) {
                    this.InfologMessageTypeField = value;
                    this.RaisePropertyChanged("InfologMessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE")]
    public interface PANGEA_MPA_SERVICE {
        
        // CODEGEN: Generating message contract since the wrapper name (PANGEA_MPA_SERVICEPANGEA_importRequest) of message PANGEA_MPA_SERVICEPANGEA_importRequest does not match the default value (PANGEA_import)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_import", ReplyAction="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_importResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.AifFault), Action="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_importAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_importResponse PANGEA_import(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_importRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_import", ReplyAction="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_importResponse")]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_importResponse> PANGEA_importAsync(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_importRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (PANGEA_MPA_SERVICEPANGEA_validateRequest) of message PANGEA_MPA_SERVICEPANGEA_validateRequest does not match the default value (PANGEA_validate)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_validate", ReplyAction="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_validateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.AifFault), Action="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_validateAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_validateResponse PANGEA_validate(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_validateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_validate", ReplyAction="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_validateResponse")]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_validateResponse> PANGEA_validateAsync(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_validateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (PANGEA_MPA_SERVICEPANGEA_processRequest) of message PANGEA_MPA_SERVICEPANGEA_processRequest does not match the default value (PANGEA_process)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_process", ReplyAction="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_processResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.AifFault), Action="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_processAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_processResponse PANGEA_process(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_processRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_process", ReplyAction="http://tempuri.org/PANGEA_MPA_SERVICE/PANGEA_processResponse")]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_processResponse> PANGEA_processAsync(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_processRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_MPA_SERVICEPANGEA_importRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_MPA_SERVICEPANGEA_importRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _parmURLFileCSV;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _parmFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _parmSeparator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string _parmGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public string _parmModule;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=5)]
        public string _parmCompany;
        
        public PANGEA_MPA_SERVICEPANGEA_importRequest() {
        }
        
        public PANGEA_MPA_SERVICEPANGEA_importRequest(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.CallContext CallContext, string _parmURLFileCSV, string _parmFileName, string _parmSeparator, string _parmGUID, string _parmModule, string _parmCompany) {
            this.CallContext = CallContext;
            this._parmURLFileCSV = _parmURLFileCSV;
            this._parmFileName = _parmFileName;
            this._parmSeparator = _parmSeparator;
            this._parmGUID = _parmGUID;
            this._parmModule = _parmModule;
            this._parmCompany = _parmCompany;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_MPA_SERVICEPANGEA_importResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_MPA_SERVICEPANGEA_importResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public PANGEA_MPA_SERVICEPANGEA_importResponse() {
        }
        
        public PANGEA_MPA_SERVICEPANGEA_importResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_MPA_SERVICEPANGEA_validateRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_MPA_SERVICEPANGEA_validateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _parmGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _parmModule;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _parmCompany;
        
        public PANGEA_MPA_SERVICEPANGEA_validateRequest() {
        }
        
        public PANGEA_MPA_SERVICEPANGEA_validateRequest(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.CallContext CallContext, string _parmGUID, string _parmModule, string _parmCompany) {
            this.CallContext = CallContext;
            this._parmGUID = _parmGUID;
            this._parmModule = _parmModule;
            this._parmCompany = _parmCompany;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_MPA_SERVICEPANGEA_validateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_MPA_SERVICEPANGEA_validateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public PANGEA_MPA_SERVICEPANGEA_validateResponse() {
        }
        
        public PANGEA_MPA_SERVICEPANGEA_validateResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_MPA_SERVICEPANGEA_processRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_MPA_SERVICEPANGEA_processRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _parmGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _parmModule;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _parmCompany;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string _parmJournal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public string _parmUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=5)]
        public string _parmAutoPost;
        
        public PANGEA_MPA_SERVICEPANGEA_processRequest() {
        }
        
        public PANGEA_MPA_SERVICEPANGEA_processRequest(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.CallContext CallContext, string _parmGUID, string _parmModule, string _parmCompany, string _parmJournal, string _parmUserId, string _parmAutoPost) {
            this.CallContext = CallContext;
            this._parmGUID = _parmGUID;
            this._parmModule = _parmModule;
            this._parmCompany = _parmCompany;
            this._parmJournal = _parmJournal;
            this._parmUserId = _parmUserId;
            this._parmAutoPost = _parmAutoPost;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_MPA_SERVICEPANGEA_processResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_MPA_SERVICEPANGEA_processResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public PANGEA_MPA_SERVICEPANGEA_processResponse() {
        }
        
        public PANGEA_MPA_SERVICEPANGEA_processResponse(string response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PANGEA_MPA_SERVICEChannel : PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PANGEA_MPA_SERVICEClient : System.ServiceModel.ClientBase<PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE>, PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE {
        
        public PANGEA_MPA_SERVICEClient() {
        }
        
        public PANGEA_MPA_SERVICEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PANGEA_MPA_SERVICEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PANGEA_MPA_SERVICEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PANGEA_MPA_SERVICEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_importResponse PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE.PANGEA_import(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_importRequest request) {
            return base.Channel.PANGEA_import(request);
        }
        
        public string PANGEA_import(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.CallContext CallContext, string _parmURLFileCSV, string _parmFileName, string _parmSeparator, string _parmGUID, string _parmModule, string _parmCompany) {
            PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_importRequest inValue = new PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_importRequest();
            inValue.CallContext = CallContext;
            inValue._parmURLFileCSV = _parmURLFileCSV;
            inValue._parmFileName = _parmFileName;
            inValue._parmSeparator = _parmSeparator;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmCompany = _parmCompany;
            PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_importResponse retVal = ((PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE)(this)).PANGEA_import(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_importResponse> PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE.PANGEA_importAsync(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_importRequest request) {
            return base.Channel.PANGEA_importAsync(request);
        }
        
        public System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_importResponse> PANGEA_importAsync(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.CallContext CallContext, string _parmURLFileCSV, string _parmFileName, string _parmSeparator, string _parmGUID, string _parmModule, string _parmCompany) {
            PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_importRequest inValue = new PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_importRequest();
            inValue.CallContext = CallContext;
            inValue._parmURLFileCSV = _parmURLFileCSV;
            inValue._parmFileName = _parmFileName;
            inValue._parmSeparator = _parmSeparator;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmCompany = _parmCompany;
            return ((PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE)(this)).PANGEA_importAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_validateResponse PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE.PANGEA_validate(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_validateRequest request) {
            return base.Channel.PANGEA_validate(request);
        }
        
        public string PANGEA_validate(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.CallContext CallContext, string _parmGUID, string _parmModule, string _parmCompany) {
            PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_validateRequest inValue = new PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_validateRequest();
            inValue.CallContext = CallContext;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmCompany = _parmCompany;
            PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_validateResponse retVal = ((PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE)(this)).PANGEA_validate(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_validateResponse> PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE.PANGEA_validateAsync(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_validateRequest request) {
            return base.Channel.PANGEA_validateAsync(request);
        }
        
        public System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_validateResponse> PANGEA_validateAsync(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.CallContext CallContext, string _parmGUID, string _parmModule, string _parmCompany) {
            PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_validateRequest inValue = new PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_validateRequest();
            inValue.CallContext = CallContext;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmCompany = _parmCompany;
            return ((PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE)(this)).PANGEA_validateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_processResponse PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE.PANGEA_process(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_processRequest request) {
            return base.Channel.PANGEA_process(request);
        }
        
        public string PANGEA_process(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.CallContext CallContext, string _parmGUID, string _parmModule, string _parmCompany, string _parmJournal, string _parmUserId, string _parmAutoPost) {
            PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_processRequest inValue = new PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_processRequest();
            inValue.CallContext = CallContext;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmCompany = _parmCompany;
            inValue._parmJournal = _parmJournal;
            inValue._parmUserId = _parmUserId;
            inValue._parmAutoPost = _parmAutoPost;
            PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_processResponse retVal = ((PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE)(this)).PANGEA_process(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_processResponse> PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE.PANGEA_processAsync(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_processRequest request) {
            return base.Channel.PANGEA_processAsync(request);
        }
        
        public System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_processResponse> PANGEA_processAsync(PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.CallContext CallContext, string _parmGUID, string _parmModule, string _parmCompany, string _parmJournal, string _parmUserId, string _parmAutoPost) {
            PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_processRequest inValue = new PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICEPANGEA_processRequest();
            inValue.CallContext = CallContext;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmCompany = _parmCompany;
            inValue._parmJournal = _parmJournal;
            inValue._parmUserId = _parmUserId;
            inValue._parmAutoPost = _parmAutoPost;
            return ((PANGEA.IMPORTSUITE.DataModel.AX_DIRECT_IMPORT.PANGEA_MPA_SERVICE)(this)).PANGEA_processAsync(inValue);
        }
    }
}
