//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PANGEA.IMPORTSUITE.DataModel.UAT {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infolog", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Infolog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANGEA.IMPORTSUITE.DataModel.UAT.InfologEntry[] EntriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANGEA.IMPORTSUITE.DataModel.UAT.InfologEntry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologEntry", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class InfologEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANGEA.IMPORTSUITE.DataModel.UAT.InfologType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANGEA.IMPORTSUITE.DataModel.UAT.InfologType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologType", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    public enum InfologType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="UAT.ImportSuiteService")]
    public interface ImportSuiteService {
        
        // CODEGEN: Generating message contract since message PANGEA_import has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteService/PANGEA_import", ReplyAction="http://tempuri.org/ImportSuiteService/PANGEA_importResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PANGEA.IMPORTSUITE.DataModel.UAT.Fault), Action="http://tempuri.org/ImportSuiteService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_importResponse PANGEA_import(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_import request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteService/PANGEA_import", ReplyAction="http://tempuri.org/ImportSuiteService/PANGEA_importResponse")]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_importResponse> PANGEA_importAsync(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_import request);
        
        // CODEGEN: Generating message contract since message PANGEA_validate has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteService/PANGEA_validate", ReplyAction="http://tempuri.org/ImportSuiteService/PANGEA_validateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PANGEA.IMPORTSUITE.DataModel.UAT.Fault), Action="http://tempuri.org/ImportSuiteService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_validateResponse PANGEA_validate(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_validate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteService/PANGEA_validate", ReplyAction="http://tempuri.org/ImportSuiteService/PANGEA_validateResponse")]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_validateResponse> PANGEA_validateAsync(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_validate request);
        
        // CODEGEN: Generating message contract since message PANGEA_process has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteService/PANGEA_process", ReplyAction="http://tempuri.org/ImportSuiteService/PANGEA_processResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PANGEA.IMPORTSUITE.DataModel.UAT.Fault), Action="http://tempuri.org/ImportSuiteService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_processResponse PANGEA_process(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_process request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteService/PANGEA_process", ReplyAction="http://tempuri.org/ImportSuiteService/PANGEA_processResponse")]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_processResponse> PANGEA_processAsync(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_process request);
        
        // CODEGEN: Generating message contract since message PANGEA_showrecords has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteService/PANGEA_showrecords", ReplyAction="http://tempuri.org/ImportSuiteService/PANGEA_showrecordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PANGEA.IMPORTSUITE.DataModel.UAT.Fault), Action="http://tempuri.org/ImportSuiteService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_showrecordsResponse PANGEA_showrecords(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_showrecords request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportSuiteService/PANGEA_showrecords", ReplyAction="http://tempuri.org/ImportSuiteService/PANGEA_showrecordsResponse")]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_showrecordsResponse> PANGEA_showrecordsAsync(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_showrecords request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_import", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_import {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _parmCompany;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _parmFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _parmGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string _parmModule;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public string _parmSeparator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=5)]
        public string _parmURLFileCSV;
        
        public PANGEA_import() {
        }
        
        public PANGEA_import(PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext, string _parmCompany, string _parmFileName, string _parmGUID, string _parmModule, string _parmSeparator, string _parmURLFileCSV) {
            this.CallContext = CallContext;
            this._parmCompany = _parmCompany;
            this._parmFileName = _parmFileName;
            this._parmGUID = _parmGUID;
            this._parmModule = _parmModule;
            this._parmSeparator = _parmSeparator;
            this._parmURLFileCSV = _parmURLFileCSV;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_importResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_importResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.UAT.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string result;
        
        public PANGEA_importResponse() {
        }
        
        public PANGEA_importResponse(PANGEA.IMPORTSUITE.DataModel.UAT.Infolog Infolog, string result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_validate", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_validate {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _parmCompany;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _parmGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _parmModule;
        
        public PANGEA_validate() {
        }
        
        public PANGEA_validate(PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmModule) {
            this.CallContext = CallContext;
            this._parmCompany = _parmCompany;
            this._parmGUID = _parmGUID;
            this._parmModule = _parmModule;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_validateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_validateResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.UAT.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string result;
        
        public PANGEA_validateResponse() {
        }
        
        public PANGEA_validateResponse(PANGEA.IMPORTSUITE.DataModel.UAT.Infolog Infolog, string result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_process", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_process {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _parmCompany;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _parmGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _parmJournal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string _parmModule;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public string _parmUserId;
        
        public PANGEA_process() {
        }
        
        public PANGEA_process(PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmJournal, string _parmModule, string _parmUserId) {
            this.CallContext = CallContext;
            this._parmCompany = _parmCompany;
            this._parmGUID = _parmGUID;
            this._parmJournal = _parmJournal;
            this._parmModule = _parmModule;
            this._parmUserId = _parmUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_processResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_processResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.UAT.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string result;
        
        public PANGEA_processResponse() {
        }
        
        public PANGEA_processResponse(PANGEA.IMPORTSUITE.DataModel.UAT.Infolog Infolog, string result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_showrecords", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_showrecords {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _parmCompany;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _parmGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _parmModule;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string _parmRegType;
        
        public PANGEA_showrecords() {
        }
        
        public PANGEA_showrecords(PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmModule, string _parmRegType) {
            this.CallContext = CallContext;
            this._parmCompany = _parmCompany;
            this._parmGUID = _parmGUID;
            this._parmModule = _parmModule;
            this._parmRegType = _parmRegType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PANGEA_showrecordsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PANGEA_showrecordsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PANGEA.IMPORTSUITE.DataModel.UAT.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string result;
        
        public PANGEA_showrecordsResponse() {
        }
        
        public PANGEA_showrecordsResponse(PANGEA.IMPORTSUITE.DataModel.UAT.Infolog Infolog, string result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImportSuiteServiceChannel : PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImportSuiteServiceClient : System.ServiceModel.ClientBase<PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService>, PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService {
        
        public ImportSuiteServiceClient() {
        }
        
        public ImportSuiteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImportSuiteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportSuiteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportSuiteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_importResponse PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService.PANGEA_import(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_import request) {
            return base.Channel.PANGEA_import(request);
        }
        
        public PANGEA.IMPORTSUITE.DataModel.UAT.Infolog PANGEA_import(PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext, string _parmCompany, string _parmFileName, string _parmGUID, string _parmModule, string _parmSeparator, string _parmURLFileCSV, out string result) {
            PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_import inValue = new PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_import();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmFileName = _parmFileName;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmSeparator = _parmSeparator;
            inValue._parmURLFileCSV = _parmURLFileCSV;
            PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_importResponse retVal = ((PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService)(this)).PANGEA_import(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_importResponse> PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService.PANGEA_importAsync(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_import request) {
            return base.Channel.PANGEA_importAsync(request);
        }
        
        public System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_importResponse> PANGEA_importAsync(PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext, string _parmCompany, string _parmFileName, string _parmGUID, string _parmModule, string _parmSeparator, string _parmURLFileCSV) {
            PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_import inValue = new PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_import();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmFileName = _parmFileName;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmSeparator = _parmSeparator;
            inValue._parmURLFileCSV = _parmURLFileCSV;
            return ((PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService)(this)).PANGEA_importAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_validateResponse PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService.PANGEA_validate(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_validate request) {
            return base.Channel.PANGEA_validate(request);
        }
        
        public PANGEA.IMPORTSUITE.DataModel.UAT.Infolog PANGEA_validate(PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmModule, out string result) {
            PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_validate inValue = new PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_validate();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_validateResponse retVal = ((PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService)(this)).PANGEA_validate(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_validateResponse> PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService.PANGEA_validateAsync(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_validate request) {
            return base.Channel.PANGEA_validateAsync(request);
        }
        
        public System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_validateResponse> PANGEA_validateAsync(PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmModule) {
            PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_validate inValue = new PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_validate();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            return ((PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService)(this)).PANGEA_validateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_processResponse PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService.PANGEA_process(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_process request) {
            return base.Channel.PANGEA_process(request);
        }
        
        public PANGEA.IMPORTSUITE.DataModel.UAT.Infolog PANGEA_process(PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmJournal, string _parmModule, string _parmUserId, out string result) {
            PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_process inValue = new PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_process();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmGUID = _parmGUID;
            inValue._parmJournal = _parmJournal;
            inValue._parmModule = _parmModule;
            inValue._parmUserId = _parmUserId;
            PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_processResponse retVal = ((PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService)(this)).PANGEA_process(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_processResponse> PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService.PANGEA_processAsync(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_process request) {
            return base.Channel.PANGEA_processAsync(request);
        }
        
        public System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_processResponse> PANGEA_processAsync(PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmJournal, string _parmModule, string _parmUserId) {
            PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_process inValue = new PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_process();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmGUID = _parmGUID;
            inValue._parmJournal = _parmJournal;
            inValue._parmModule = _parmModule;
            inValue._parmUserId = _parmUserId;
            return ((PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService)(this)).PANGEA_processAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_showrecordsResponse PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService.PANGEA_showrecords(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_showrecords request) {
            return base.Channel.PANGEA_showrecords(request);
        }
        
        public PANGEA.IMPORTSUITE.DataModel.UAT.Infolog PANGEA_showrecords(PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmModule, string _parmRegType, out string result) {
            PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_showrecords inValue = new PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_showrecords();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmRegType = _parmRegType;
            PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_showrecordsResponse retVal = ((PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService)(this)).PANGEA_showrecords(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_showrecordsResponse> PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService.PANGEA_showrecordsAsync(PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_showrecords request) {
            return base.Channel.PANGEA_showrecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_showrecordsResponse> PANGEA_showrecordsAsync(PANGEA.IMPORTSUITE.DataModel.UAT.CallContext CallContext, string _parmCompany, string _parmGUID, string _parmModule, string _parmRegType) {
            PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_showrecords inValue = new PANGEA.IMPORTSUITE.DataModel.UAT.PANGEA_showrecords();
            inValue.CallContext = CallContext;
            inValue._parmCompany = _parmCompany;
            inValue._parmGUID = _parmGUID;
            inValue._parmModule = _parmModule;
            inValue._parmRegType = _parmRegType;
            return ((PANGEA.IMPORTSUITE.DataModel.UAT.ImportSuiteService)(this)).PANGEA_showrecordsAsync(inValue);
        }
    }
}
